apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::617952380396:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17S6955TGSV2F
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2019-12-15T19:41:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "826"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: dcfb4bbf-1f72-11ea-8301-0ad90849bd34
